#!/usr/bin/perl
=head1 NAME
Speedtest with speedtest-cli.

=head1 CONFIGURATION
Create a cron job to run 'speedtest-cli --simple' and pipe to a file on a periodic basis.
ln -s /usr/libexec/munin/plugins/speedtest /etc/munin/plugins/speedtest

Change the $speedtestLog variable below to point to your speedtest-cli log.
=cut

if($ARGV[0] eq "config"){
        print "graph speedtest\n";
        print "graph_title Speedtest\n";
        print "graph_vlabel Mbits/s\n";
        print "graph_category network\n";
        print "graph_args --base 1024\n";
        print "ping.label Ping\n";
        print "downloadSpeed.label Download Speed\n";
        print "downloadSpeed.warning 50:\n";
        print "uploadSpeed.label Upload Speed\n";
        print "uploadSpeed.warning 10:\n";

        exit;
}

$speedtestLog = "/home/clete2/speedtests.txt";
open FILE, $speedtestLog;

my $ping;
my $downloadSpeed;
my $uploadSpeed;
while(my $line = <FILE>){
        if($line =~ /Ping:\s(\d+\.\d+)\sms/i){
                $ping = $1;
        }elsif($line =~ /Download:\s(\d+\.\d+)\sMbits\/s/i){
                $downloadSpeed = $1;
        }elsif($line =~ /Upload:\s(\d+\.\d+)\sMbits\/s/i){
                $uploadSpeed = $1;
        }
}

print "ping.value $ping\n";
print "downloadSpeed.value $downloadSpeed\n";
print "uploadSpeed.value $uploadSpeed\n";
